### PR TITLE
Add thumbnail when site is shared

### PR DESCRIPTION
**Pull request by atavism**
This adds a thumbnail whenever the website is posted to FB. The current behavior is no image is shown at all.

### CODE REVIEW

**Comment by myleshorton** [comment]
Cool. @atavism  you mind also changing the links to hit lantern-installer\* instead of lantern-installer-beta*?

**Comment by atavism** [comment]
@myleshorton Done!

**Comment by myleshorton** [comment]
Nice thanks! Actually just one more thing -- can you also add that FB pixel Mo mentioned?

**Comment by atavism** [comment]
@myleshorton Done

**Comment by myleshorton** [comment]
Awesome LGTM! Merging.

**Pull request merged**
