### PR TITLE
Allow Download for other platform

### PR DESCRIPTION
**Pull request by sijad**

### CODE REVIEW

**Comment by fffw** [comment]
Thanks for your PR @sijad. Changes are good but it's more a design choice to show less elements on the page. It would be cool if there's a neat design providing such feature while keeping current conciseness and consistency, but we'd better keep it as is until we have that polished design.

**Comment by sijad** [comment]
@fffw do you have any idea in mind? I'd love work on this. Please let me know

**Comment by sijad** [comment]
Please keep in mind this PR is related to #33 also I think is still looks simple. IMO current deaign is not very good after adding android download button

**Comment by carsonefv** [comment]
Thanks for the suggestion @sijad ! We are actually in the process of redoing the website altogether, so the buttons and everything else will be changing soon. We will consider your advice for labeling the other platforms.

**Comment by sijad** [comment]
I'll look into it, thank for reviewing my codes :smile:

**Pull request closed without merging**
