### PR TITLE
[WIP] Update text

### PR DESCRIPTION
**Pull request by cosmicespresso**
This is incomplete because I'm not sure how this website and particularly the translations are supposed to work. 

- We have both an English and a Chinese hard coded website, as well as translations for these languages. I assumed I should update those `index.html` files first, is that correct?
- How do these translation files work? If I update a string in the `src/en/index.html` file, does that mean I have to update it in every single JSON file that depends on it? 
- I can't `deploy-beta` since I don't have the `s3cmd --configure` values - the ones in the `S3 website` entry of 1Password don't seem to work. 

Please advise 🙏

### CODE REVIEW

**Comment by oxtoacart** [comment]
> * We have both an English and a Chinese hard coded website, as well as translations for these languages. I assumed I should update those `index.html` files first, is that correct?

Yes, I believe the distinct index.html files have a few slightly different links and/or images or something but both rely on the translations.

**Comment by oxtoacart** [comment]
> * How do these translation files work? If I update a string in the `src/en/index.html` file, does that mean I have to update it in every single JSON file that depends on it?

I don't think you have to update the other JSONs manually, just run `tx push -s` and then later once the translations are available pull with `tx pull --minimum 100`

**Comment by oxtoacart** [comment]
> * I can't `deploy-beta` since I don't have the `s3cmd --configure` values - the ones in the `S3 website` entry of 1Password don't seem to work.

I've updated the entry in 1Password with what I believe is the correct secret key.

**Comment by cosmicespresso** [comment]
> > * I can't `deploy-beta` since I don't have the `s3cmd --configure` values - the ones in the `S3 website` entry of 1Password don't seem to work.
> 
> I've updated the entry in 1Password with what I believe is the correct secret key.

The error I get is `ERROR: Test failed: [Errno 8] nodename nor servname provided, or not known`. Are the following correct?

Screen Shot 2021-04-22 at 5 36 05 PM

> > * We have both an English and a Chinese hard coded website, as well as translations for these languages. I assumed I should update those `index.html` files first, is that correct?
> 
> Yes, I believe the distinct index.html files have a few slightly different links and/or images or something but both rely on the translations.

Hm that's weird - to me it looks like `en_US.json` is generated from the HTML - if I delete its contents and do `make run`, it gets repopulated.

**Comment by oxtoacart** [comment]
The main thing I have that's different is that I've got GPG configured.

**Comment by oxtoacart** [comment]
I verified that I can deploy your branch to beta @Kallirroi, so it's not a problem with your changes.

**Comment by cosmicespresso** [comment]
> I verified that I can deploy your branch to beta @Kallirroi, so it's not a problem with your changes.

Thank you! 🙂

**Comment by myleshorton** [comment]
This generally looks good to me @Kallirroi I think the only thing is just waiting on some translations!

**Review by myleshorton — APPROVED** [review]

**Comment by cosmicespresso** [comment]
@oxtoacart @myleshorton does one of you mind deploying this branch to beta? I can't get `s3cmd` to work properly. 
Thank you! 🙏

**Comment by oxtoacart** [comment]
This has been deployed to beta

**Comment by oxtoacart** [comment]
Changes on beta site passed review, I'm merging and deploying. Thanks @Kallirroi !

**Pull request merged**
