### PR TITLE
wip adding zh_HK page

### PR DESCRIPTION
**Pull request by joesis**
Resolves https://github.com/getlantern/lantern-internal/issues/3932

Two outstanding work:
1. Update the icons based on Zepkin resources. @Derekf5 please allow me to access https://zpl.io/25RPBZW

1. Determine the look and feel of the first feature column. @Derekf5 could you recommend on the icon to use for the list items, and other adjustments? Here's @discord1024 's rough idea

   image

   and here's what it looks like for now
   image

### CODE REVIEW

**Comment by joesis** [comment]
Also should we make the links stand out a bit? Here's are the effect of underline and bold respectively @Derekf5 

image

**Comment by discord1024** [comment]
For the X, @Derekf5 I think we need a crossout sign rather than a bullet point. 

I guess we can make the link blue so everyone know it's a link.

**Comment by Derekf5** [comment]
Screen Shot 2020-07-13 at 11 45 17 AM

Here is what it can look like @joesis, pretty much what you had with a couple of small adjustments.

1. Links can be underlined and color: #00BCD4
2. Instead of bullet points, they can be a Bold X's as @discord1024 suggested, color: #DB0A5B
3. '藍燈不記錄' text should be left-aligned with the X's

**Comment by joesis** [comment]
Merging and deploying. Please check https://getlantern.org/zh_HK/index.html

**Comment by joesis** [comment]
Failed to deploy because of "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'getlantern.org.s3.amazonaws.com'". Checking what's going on

**Comment by joesis** [comment]
Okay done deploying

**Pull request merged**
